[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ai_trading_bot"
version = "0.1.0"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["."]
include = ["ai_trading_bot*"]
exclude = ["tests*"]
