[logger]
level = "error"           # quiet default logs (error-only)

[server]
runOnSave = false          # avoid hot-reload spam
headless = true            # good for terminals

[browser]
gatherUsageStats = false   # privacy, fewer notices

